### ISSUE TITLE
Filter is not working if ximgdiff is disabled

### ISSUE THREAD

**Issue by stevschmid** [reg-viz/reg-cli-report-ui#28]
## Describe the bug

If `ximgdiff` is disabled in `regconfig.json`, filtering in the generated HTML report is not working.

## Reproduced step

Check out `reg-cli-report-ui`, disable ximgdiffConfig in `develop/index.html`

```javascript
ximgdiffConfig: { enabled: false, workerUrl: './worker.js' },
```

Start the dev env via `yarn start`. Filtering is not working.

## Cause

https://github.com/reg-viz/reg-cli-report-ui/blob/73849dfa8bfc09497706f4fd0f1b47fe36683a88/src/worker-client.ts#L44-L46 

 `this._worker` is only created if ximg diff is enabled. Since `this._worker` is used to relay the `filtering` messages, the filtering is not working if `XIMGDiffConfig.enabled = false`

## Expected behavior

Filtering is working even with ximgdiff disabled.

## Actual behavior

Filtering is not working with ximgdiff disabled.

**Comment by stefanteixeira** [comment]
I'm using Loki for visual regression testing, but I'm using `reg-cli` for reporting, as some other Loki users are doing (found about reg-cli in this issue https://github.com/oblador/loki/issues/76).

I'm experiencing the same issue with filtering, it would be helpful to have it working or at least have a workaround. Could someone please check on this?
